### ISSUE TITLE
Improve "Enter password for pool/dataset" dialog usability

### ISSUE THREAD

**Issue by lzhang10** [cbreak-black/ZetaWatch#10]
Running version 43 and I have a usability improvement request.

I have a couple of encrypted pools. Upon login, there is an "Enter password for pool/dataset" dialog popping up and grabs focus of the cursor. Since I use keychain to remember passwords I just let it do its thing until all the encrypted datasets are open and mounted.

However, it usually takes anywhere between 10 to 20 seconds to import and open all my encrypted datasets, across a couple of SSDs. If a family member uses the computer he or she will start a browser by then and accidentally type into the password dialog (because it has focus) without realizing so. Then I will be told the browser does not work. 

I think if keychain is used most of time the dialog can be replaced by a notification window saying something like "Opening pool/dataset..." without needing to grab the focus, and affecting the user's action while the dialog is open.

So can I suggest the following UI improvement?
1. Unlock the encrypt dataset using a notification instead of a dialog that grabs focus, if keychain is used.
2. Only pop up a dialog asking for password when step 1 fails, or when keychain is not used.

**Comment by lzhang10** [comment]
I hit the wrong button before finishing the issue. I have since updated the issue.

**Comment by cbreak-black** [comment]
ok

**Comment by cbreak-black** [comment]
Please give https://github.com/cbreak-black/ZetaWatch/releases/tag/r44 a try. It should no longer grab focus, and the dialog will only contain an editable password box if a password is requested. I've decided to still use the box for loading to keep the interaction more streamlined.

Internally, each filesystem is first checked for using a file key, and if that is not the case or fails, for stored password, and then user interactive.

**Comment by lzhang10** [comment]
Thanks for the quick release. I checked out r44. It works better in the sense the input box no longer grab focus. However, I noticed if I launch Firefox and start to type in the address bar before the ZFS datasets are opened, for a brief moment when the now improved dialog shows up, the focus is shifted from Firefox to the checkbox on the ZetaWatch dialog.

I think that's because the dialog is displayed at the top of the window stack and hence still gets focus. Not sure what an ideal solution would be though.

**Comment by cbreak-black** [comment]
Hmm... maybe I can just disable interaction of the whole dialog. I'd prefer to not show / hide it as I go through the datasets, but that'd be an other option.

**Comment by lzhang10** [comment]
I agree it's not a good idea to show/hide the dialog frequently either.

If you leave the checkbox grayed out until needed maybe it will not grab focus? With r44 it is the checkbox that got focus upon showing up. 

I'm fine with the r44 as is if there is no better solution. It is less obstructive than r43 for sure.

**Comment by cbreak-black** [comment]
I also disabled the checkbox in r45: https://github.com/cbreak-black/ZetaWatch/releases/tag/r45

**Comment by lzhang10** [comment]
Thanks for sending this update. I tested the r45. I was typing in the browser's address bar as soon as I login. When the dialog popped up the focus was shifted to the dialog and the browser lost the focus. If the user continued typing MacOS gave some audible feedback because nothing has focus on the dialog.

I think this is better than r44, where if space key was hit while the focus is on the dialog the checkbox would be toggled.
