### ISSUE TITLE
add option and menu entry to import pool / mount datasets as readonly

### ISSUE THREAD

**Issue by mmoole** [cbreak-black/ZetaWatch#11]
this is a feature request:
after importing a pool, not only Spotlight and Finder notoriously grab the disk and do their things, but maybe I also want to import a pool that contains backups read-only.
Having the option to import as read-only in the menu would be a great time-saver for that.
Additionally there could be a setting to default to read-only import when host-id doesn't match. 
And eventually, one could want to write on a pool that was imported as read-only - then a menu entry for remounting with write access would be totally awesome.

greetings 👍

**Comment by cbreak-black** [comment]
Hi

I think you can make datasets import readonly by default by setting their `readonly` property. This property can be set temporarily at import time, so I think I can make a `readonly=on` / `readonly=off` import functionality too.

This is different from importing the pool as readonly by the way, it only affects mounting.

**Comment by cbreak-black** [comment]
So, Just released https://github.com/cbreak-black/ZetaWatch/releases/tag/r46, it adds the ability to import pools as read-only or read-write, so you can set the default property to `readonly=on` (which will be honored by auto-import), and import it read-write when desired, or vice-versa. I hope this solves your problem :)
