### ISSUE TITLE
Big Sur and OpenZFS 2 support

### ISSUE THREAD

**Issue by dguisinger** [cbreak-black/ZetaWatch#13]
ZetaWatch doesn't start on Big Sur and needs to be updated for Big Sur and OpenZFS 2.0

**Comment by cbreak-black** [comment]
ZFS itself hasn't been released for Big Sur either, and I don't have access to a system capable of running it easily. I'll get around to do this eventually, but don't hold your breath.

**Comment by derbroti** [comment]
Just for completeness (I didn't find it at first).
There is a release version - though, it is not yet publicly announced:

https://openzfsonosx.org/forum/viewtopic.php?f=20&t=3478

**Comment by rdmitry0911** [comment]
> ZFS itself hasn't been released for Big Sur either, and I don't have access to a system capable of running it easily. I'll get around to do this eventually, but don't hold your breath.

If this helps, I can provide you with access to a virtual machine running big sur for making a big sur release of zetawatch.

**Comment by cbreak-black** [comment]
OpenZFS 2.0 should now be supported with https://github.com/cbreak-black/ZetaWatch/releases/tag/r48, this might or might not work on BigSur. If it doesn't, comment here.
