### ISSUE TITLE
Zetawatch r47 and OpenZFS2.0.1 issues

### ISSUE THREAD

**Issue by zoeloe** [cbreak-black/ZetaWatch#14]
Hi,
it seems that ZetaWatch want to use libraryes in /usr/local/lib (like e.g. ./ZetaWatch 
dyld: Library not loaded: /usr/local/lib/libzpool.1.dylib
  Referenced from: /Applications/ZetaWatch.app/Contents/MacOS/./ZetaWatch
  Reason: image not found
Abort trap: 6

It seems that the newer OpenZFS installs libraries in /usr/local/zfs/lib
This was NOT the case is OpenZFS 1.9.4 where the libraries are installed in /usr/local/lib
Also: Zetawatch needs libzpool.1.dylib
but in OpenZFS 2.0.1 this lib has a newer version libzpool.4.dylib

Hope this helps

**Comment by cbreak-black** [comment]
Hi

There's the experimental branch `zfs-2.0`, which already has many of the changes required to build ZetaWatch for the new version. Using the new library locations and linking to the new versions was easy, but there were some other changes that lead to API incompatibilities, which were hard to spot. So I don't think the work for porting is done. And since 2.0 used to not run reliably on my system, and I couldn't test it properly, I didn't spend more time on the port.

**Comment by zoeloe** [comment]
Oh dear me.. I missed that branch...Thanks for the pointer.
After avoiding the Signing errors it builds on Catalina 10.15.7 with Xcode 12.4,... but bombs with:
dyld: Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /Users/......./Library/Developer/Xcode/DerivedData/ZetaWatch-bbtqlezzyyoelzhaenjixngtklwt/Build/Products/Debug/ZetaWatch.app/Contents/MacOS/ZetaWatch
  Reason: image not found
(lldb)

**Comment by zoeloe** [comment]
Ahha,... Sparkle.Framework Zetwatch General build settings,... Embed without signing..... Build successfull
With one warning in Xcode:
2021-06-09 16:47:18.588156+0200 ZetaWatch[55498:603654] [Sparkle] DEPRECATION: SUUpdater is deprecated in Sparkle 2 but functional for transitional purposes. Please migrate to SPUStandardUpdaterController as a nib instantiated replacement, or SPUUpdater.

**Comment by cbreak-black** [comment]
I released https://github.com/cbreak-black/ZetaWatch/releases/tag/r48, which seems to work with 2.0.

**Comment by zoeloe** [comment]
Seems to run on Catalina latest. Thanks. Much appreciated !
The previous post where I mentioned that the branch build worked,.. did have some switch case warnings in ZFSwrapper indeed, but did compile...  and run... If interested give a yell and I'll zip the thing for you to compare if needed.
Great interface and project.
