### ISSUE TITLE
load/unload encryption keys doesn't work

### ISSUE THREAD

**Issue by rdmitry0911** [cbreak-black/ZetaWatch#15]
I moved from zfs 1.9.4 to zfs 2.0.1. on Catalina. Everything went well. I exported my pools, then I upgraded them and now I can mount my encrypted zfs volumes manually with sudo zfs mount -l 
However, when I'm trying to load/unload mount/unmount volumes from zetawatch it does not do anything. The volumes still are unmounted/mounted and keys are uloaded/loaded after these operations. In 1.9.4 everything worked fine.

**Comment by cbreak-black** [comment]
That's weird. For me, loading / unloading of keys, as well as mounting / unmounting works.

Which version of ZetaWatch do you use?

Does uninstalling the helper help?

```
launchctl unload /Library/LaunchDaemons/net.the-color-black.ZetaAuthorizationHelper.plist
rm /Library/LaunchDaemons/net.the-color-black.ZetaAuthorizationHelper.plist
rm /Library/PrivilegedHelperTools/net.the-color-black.ZetaAuthorizationHelper
```

**Comment by rdmitry0911** [comment]
Yes, uninstalling helper first solves the problem. Thank you.
