### ISSUE TITLE
Compatability with OpenZFS 2.1.0

### ISSUE THREAD

**Issue by thecodehen** [cbreak-black/ZetaWatch#16]
When opening ZetaWatch, it produces a `dyld: Library not loaded: /usr/local/zfs/lib/libzpool.4.dylib` error. Under `/usr/local/zfs/lib/` you do see `libzpool.5.dylib` instead. Maybe a version bump from v4 to v5 would work?

Context: I upgraded OpenZFS from 2.0.1 to 2.1.0.

**Comment by cbreak-black** [comment]
What will be needed is recompiling with the new library (and possibly fixing incompatibility issues). I'll do this as soon as I find time, now that 2.1 has been released. The binding to 4 happens automatically, since that was what it was linked to.

**Comment by cbreak-black** [comment]
Alright, the new release supports 2.1.
https://github.com/cbreak-black/ZetaWatch/releases/tag/r49
