### ISSUE TITLE
OpenZFS 2.1 support seems to break ZetaWatch on M1 Big Sur Mac

### ISSUE THREAD

**Issue by JMoVS** [cbreak-black/ZetaWatch#17]
Hi @cbreak-black,

after updating to the 2.1 OpenZFS support version, it seems like it is not even launching anymore. I attached the crash report
[ZetaWatch_2021-08-28-181453_Sergeant-Peppair.log](https://github.com/cbreak-black/ZetaWatch/files/7071015/ZetaWatch_2021-08-28-181453_Sergeant-Peppair.log)

**Comment by cbreak-black** [comment]
The new build is built for intel, not arm. Your crash report shows issues with loading OpenZFS libs, which are not intel.

**Comment by spaxxilein** [comment]
Will Zetawatch be ported to M1 anytime soon? Regards, spaxxilein

**Comment by cbreak-black** [comment]
Yeah...

https://github.com/cbreak-black/ZetaWatch/releases/tag/r49-arm

It's not tested at all though.

**Comment by spaxxilein** [comment]
> Yeah...
> 
> https://github.com/cbreak-black/ZetaWatch/releases/tag/r49-arm
> 
> It's not tested at all though.

Works for me - anything specific i can test for you? Regards, spaxxilein

**Comment by cbreak-black** [comment]
> > Yeah...
> > https://github.com/cbreak-black/ZetaWatch/releases/tag/r49-arm
> > It's not tested at all though.
> 
> Works for me - anything specific i can test for you? Regards, spaxxilein

No, if it works that's exactly how it should behave :)

**Comment by spaxxilein** [comment]
> > > Yeah...
> > > https://github.com/cbreak-black/ZetaWatch/releases/tag/r49-arm
> > > It's not tested at all though.
> > 
> > 
> > Works for me - anything specific i can test for you? Regards, spaxxilein
> 
> No, if it works that's exactly how it should behave :)

Unfortunatly i cannot import pools when booting. It just shows: Importable pools: no importable pools found.

I think this might be a permission problem? Do you have any suggestion how to fix this problem?
