### ISSUE TITLE
zpools renamed and i/o errors

### ISSUE THREAD

**Issue by ryjorny** [cbreak-black/ZetaWatch#2]
I've had a great experience with ZFS up until something strange happened. I downloaded the ZetaWatch r9 binary to help me manage my zpools at boot. I have 4 pools of mirrored vdevs and they each have an encrypted dataset except for the first one I will mention where I store data directly on the pool (Fentanyl 2x1.5TB SATA motherboard controller, Ketamina 2x3TB SATA motherboard controller, Diprivan 2x3TB LSI PCIe SAS HBA, Midazolam 2x3TB LSI PCIe SAS HBA). I ran ZetaWatch and it failed to import the pools that had an encrypted dataset on it but it did report that the plain unencrypted pool Fentanyl was OK.

After this I tried to zpool import -a and got an error "zfs: cannot import Diprivan: I/O error Destroy and re-create the pool from a backup" and the same error for Midazolam. I exported all pools and rebooted. This time Fentanyl still worked fine and Midazolam was able to be imported with zpool import Midazolam and the encrypted dataset within mounted, but Diprivan had the same I/O error. Ketamina no longer existed at all. It wasn't in disk utility and when I ran diskutil list the two disks that used to be called Ketamina are now called Midazolam also. Four disks in diskutil were reporting their names as Midazolam. I exported everything, shutdown and removed the disks that make up my two working pools, Fentanyl and Midazolam. I rebooted and tried to import Ketamina, "no pool exists..." and when I tried to import Midazolam (falsely named) I got "cannot import 'Midazolam': one or more devices is currently unavailable". I have not tried to fix Diprivan yet fearing I could make this situation worse so only work with one at a time.

Reading up on the FreeNAS and zfsonlinux boards haven't given me any leads. Thank you for your time and any ideas you can give me how to fix this.

ZetaWatch r9
macos high sierra 10.13.6
OpenZFS on OS X 1.8.2

**Comment by cbreak-black** [comment]
Hi

That sounds all very strange. Are you sure your underlying disks are working and the SATA/SAS card is working? ZetaWatch doesn't do anything advanced itself, it just calls out to the ZFS Libraries to do any work, so there should be little difference in what the command line and ZetaWatch does with respect to importing.

But if devices are not listed in diskutil list, then ZetaWatch can't import pools stored on them. The "import all" function basically does the same as zpool import -a on the command line. Afterwards, the pools that have been imported should show up both in the menu and zpool status.

ZetaWatch does not support renaming pools. I don't plan to add this functionality either. You can use the command line for this.

**Comment by ryjorny** [comment]
Yes I skimmed through the ZetaWatch code and didn't see anything that jumped out at me. I can confirm the SAS HBA is working (other than reporting internal drives as external) as I have switched out the drives numerous times since then using both internal 8087 ports. Running "diskutil list" returns expected values which I have in the link below.

I am also working with Mr. Lundman on the ZFS for Mac forums if you are interested in what I have attempted thus far https://openzfsonosx.org/forum/viewtopic.php?f=26&t=3236 . I did nothing different yesterday other than run ZetaWatch and attempt to mount the pools from the menu bar. When that failed to import the zpools with encrypted datasets I returned to terminal and did what I have always done successfully in the past "sudo zpool import -a && sudo zfs mount -a -l" which is when I got the errors.

**Comment by cbreak-black** [comment]
From your description it looks like your issues are unrelated to ZetaWatch. I import and mount datasets with ZetaWatch all the time without such problems. You should try to use the command line, zpool status, zpool import and maybe zdb -l. If you have the option, trying to import the pool with other systems might also give some insight. But as of now, my hypothesis is that your pools died to something hardware or zfs driver related.

**Comment by ryjorny** [comment]
I attempted as much command line wizardry as I could find from O3X, ZoL and FreeBSD forums.
I went to the system I created these pools on since the /etc/zfs/zpool.cache file on my machine is broken. In this text file I have the pool info at creation and the current output from diskutil info.
The UUIDs reported have gotten associated with different volume names. Do you know how I could re-associate them with the correct disks? I bet if I could do that the metadata checks would work and the pools would be happy again.

[ryjornyZFS.txt](https://github.com/cbreak-black/ZetaWatch/files/2593207/ryjornyZFS.txt)

**Comment by cbreak-black** [comment]
The volume names don't matter, you can ignore them.
But it seems your pool is there, since zdb shows it. Does zpool status also show it?

**Comment by cbreak-black** [comment]
Doesn't seem ZetaWatch related in any case.
