### ISSUE TITLE
Loading encrypted ZFS enters infinite loop

### ISSUE THREAD

**Issue by thecodehen** [cbreak-black/ZetaWatch#20]
After upgrading to ZFS 2.1.0, I was able to `zfs mount -l` my partitions. However, if I mount the disk via ZetaWatch, it would enter an infinite loop. Any fix for this?

<img width="543" alt="image" src="https://user-images.githubusercontent.com/6582598/144339549-90a1d731-00f6-4c2a-9751-fb5d8fd93137.png">

**Comment by cbreak-black** [comment]
Wasn't able to reproduce this.
