### ISSUE TITLE
Can't mount snapshot

### ISSUE THREAD

**Issue by defder-su** [cbreak-black/ZetaWatch#26]
Nothing happens.

**Comment by cbreak-black** [comment]
This is unfortunately working as intended. Back when I implemented it, finder never showed the mounted snapshots, even when they did show up as correctly mounted on the commandline. Clones should work.

**Comment by defder-su** [comment]
> Finder never showed the mounted snapshots

Is it accessible from CLI? I can't find (though saw such topic somewhere in www).
'zfs get mountpoint' for snapshots returns empty, and 'zfs set mountpoint' outputs 'this property can not be modified for snapshots'.
Ideally, if ZetaWatch will output mountpoint path making able to copy it to use with CLI (e.g., mc) or with some alternate file manager.

**Comment by cbreak-black** [comment]
Snapshots are mounted inside each dataset, in the `.zfs/snapshot` directory. That directory is not visible in `ls`, but you can `cd` into it. On some systems, these are auto-mounted by default. But either way, MacOS' Finder doesn't show them, so you should clone the snapshots if you want to access files via it.

**Comment by defder-su** [comment]
`cd .zfs/snapshot && open .` opens mounted snapshots in Finder (macOS 10.13).

So, the app could perform `cd .zfs/snapshot/<snapshot> && open .` when mounted.

**Comment by defder-su** [comment]
Hmm... It worked, but now all mounted became just empty folders. I believe it will work again after restart macOS though.

**Comment by cbreak-black** [comment]
The GUI was never reliably able to look at mounted snapshots. Not even with `snapdir=visible`. Clone the snapshot if you want to look at snapshots in the GUI.
