### ISSUE TITLE
zfs-macOS-2.1.6 release breaks Zetawatch

### ISSUE THREAD

**Issue by benjamindonnachie** [cbreak-black/ZetaWatch#28]
After upgrading to zfs-macOS v2.1.6 release (https://openzfsonosx.org/forum/viewtopic.php?f=20&t=3743), Zeta watch fails to load pool configuration with a heap of error messages about data structure mismatches.

For example:

![image](https://user-images.githubusercontent.com/83379521/205441547-779ea193-8684-4fdf-ad80-77034253b88a.png)

**Comment by cbreak-black** [comment]
This is expected. 2.1.6 changed several internal data structures, and for safety, ZetaWatch tries to detect this and fails if it's the case. 2.1.6 won't be supported without at least recompiling, but likely code changes are needed. I tried to do that last week, without success (missing headers), and plan to try again with the release version soon.

**Comment by cbreak-black** [comment]
Give https://github.com/cbreak-black/ZetaWatch/releases/tag/r50 a try

**Comment by benjamindonnachie** [comment]
Works perfectly again - many thanks!
