### ISSUE TITLE
Rejecting /usr/local/lib/libzpool.1.dylib

### ISSUE THREAD

**Issue by greg-fischer** [cbreak-black/ZetaWatch#3]
Zetawatch does not launch. I see the following in console.

Library Validation failed: Rejecting '/usr/local/lib/libzpool.1.dylib' (Team ID: none, platform: no) for process 'ZetaWatch(14032)' (Team ID: 8THUW5GT6P, platform: no), reason: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

I authorized the popup when originally launched, but still get this and no other popups. Nothing showing in Privacy settings requesting auth either.

I'm using 10.14.4.  OpenZfs OSX 1.7.4.
Just installed the r13 version.

**Comment by cbreak-black** [comment]
The latest version of ZetaWatch will only work with OpenZFS OS X 1.9, if you want to support an older version, you'll have to remove some features and recompile it.

But the error message seems to be about the new authentication hardening in 10.14, your OpenZFS version isn't code signed. This doesn't seem to be a problem on 10.13, where I am, but maybe apple got more picky. Can you try to use a newer build of ZFS, one that lundman code signed?

https://openzfsonosx.org/forum/viewtopic.php?f=20&t=3271

**Comment by greg-fischer** [comment]
Yeah I'll try the 1.9 version (like you said on the other issue).  I was just hanging on to 1.7x becasue 1.8x was crashing on my Mojave, and 1.7x was stable for me. I'll get it updated and test it later this week and report back.
Thanks again!

**Comment by cbreak-black** [comment]
I added an additional entitlement for linking to libraries, and it should have resolved this issue, check out [r14](https://github.com/cbreak-black/ZetaWatch/releases/tag/r14), see commit 342c9db6c8a21464e0c9be2b17bc314c4e50be15.

**Comment by greg-fischer** [comment]
1.9.0 and r14 are working great. thanks!
