### ISSUE TITLE
Export options (enhancement)

### ISSUE THREAD

**Issue by cahukS** [cbreak-black/ZetaWatch#5]
This a feature request: is there a plan to add an option to export imported pools?

**Comment by cbreak-black** [comment]
Hi, I added this feature in [r13](https://github.com/cbreak-black/ZetaWatch/releases/tag/r13), together with scrubbing.

**Comment by cahukS** [comment]
Thanks, still using an older version and forgot to check the release notes. Can r13 be used on OpenZFS OS X 1.8.2?

**Comment by cbreak-black** [comment]
Only if you recompile, and remove a bit of code. The ABI changed since then I think.
Edit: I uploaded a build for 1.8.1, try it ;)
