### ISSUE TITLE
List available pools and do not mount on import (Feature Request)

### ISSUE THREAD

**Issue by greg-fischer** [cbreak-black/ZetaWatch#6]
Maybe down the road, but I would find it helpful to have the option to list any available pools that can be imported and also selectively import them. I don't necessarily want to import all pools. Also, maybe "Import (Do not mount)" option.

Great little helper program so far!!

**Comment by cbreak-black** [comment]
I was thinking of adding this feature, but enumerating importable pools is expensive, so I don't want to do it on every menu open (which is when I normally query everything). I have to find out how to create sub-menus on demand.
Maybe it's sufficient to implement some NSMenu subclass with a custom submenuAction...

**Comment by cbreak-black** [comment]
A second issue is that enumerating importable pools requires elevated privileges, so I have to somehow put that into the agent.

**Comment by cbreak-black** [comment]
Was easier than I thought, see 7d8e274c for details. I made a new release that can import pools on demand. Importing without mounting... maybe later :)
