### ISSUE TITLE
import pool with alternate root

### ISSUE THREAD

**Issue by whizzrd** [cbreak-black/ZetaWatch#7]
Auto-importing may produce unexpected results when foreign pools are mounted over the current filesystem

It would be nice if ZetaWatch provided an option to mount with alternate root for some or all pools when auto-importing; either by default in /mnt : zpool import -R /mnt pool
or user-configurable

**Comment by cbreak-black** [comment]
That's an interesting idea. I'll implement that eventually :)

**Comment by cbreak-black** [comment]
So, I've added altroot support in https://github.com/cbreak-black/ZetaWatch/releases/tag/r35, give it a try. I did test it myself for a few minutes too :D

For now, you can only set a default altroot for all imports. I'm not sure if that really makes sense, but it should be a nice basis for testing.

**Comment by whizzrd** [comment]
I did some testing, using a ZFS pool named ZSD used on FreeBSD 11.2 ARMv6 RPI-B

Enabled the altroot in Zetawatch settings > more setting> [v]Use Altroot: Volumes

ZetaWatch auto mounts the pool but displays a notification:
ZetaWatch Error
ZSD: cannot mount '/usr/ports' (failed to create mountpoint). 

```sh
 # /usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" /Applications/ZetaWatch.app/Contents/Info.plist 
35
```

```sh
# zfs -V
zfs-1.9.2-0
zfs-kmod-1.9.2-0
```

Altroot seems to be set on the pool
```sh
# zpool list
NAME   SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
ZSD   14.5G  2.41G  12.1G        -         -     6%    16%  1.00x  ONLINE  /Volumes
```

Altroot is prepended before datasets with mount points
```sh
# zfs list
NAME                 USED  AVAIL  REFER  MOUNTPOINT
ZSD                 2.41G  11.6G    24K  none
ZSD/root             735M  11.6G    23K  none
ZSD/root/tmp        2.09M  11.6G  2.09M  /Volumes/mnt/tmp
ZSD/root/usr         733M  11.6G    23K  none
ZSD/root/usr/ports   733M  11.6G   733M  /Volumes/usr/ports
ZSD/rpi-b           1.69G  11.6G  1.27G  -
```

**Comment by cbreak-black** [comment]
It seems I have to manually incorporate the altroot when mounting too, and can't rely on the mountpoints being adjusted when querying zfs api. So... setting the altroot had no influence on the pool's mountpoints when mounting with ZetaWatch... I'll fix that next release :)

**Comment by cbreak-black** [comment]
So, https://github.com/cbreak-black/ZetaWatch/releases/tag/r36 fixes some issues with altroot. Turns out those were caused by me keeping a LibZFS handle around and using it over the lifetime of the program. That handle cached pool and dataset information, which lead it to get the incorrect mountpoints.
I'm not sure if that caused your problem, but it seems related.

**Comment by whizzrd** [comment]
Thank you, It's working fine now.
