### ISSUE TITLE
Can't understand the install process

### ISSUE THREAD

**Issue by UnConundrum** [cbreak-black/ZetaWatch#8]
I guess I'm obtuse, but I just don't understand.  I cloned the repo, copied the full ZetaWatch directory tree to /Users/<me>/Applications, but I don't know where to go from there....  I don't see anything starting automatically.  I've rebooted, double clicked on ZetaWatch ...  I'm out of ideas.

**Comment by cbreak-black** [comment]
The ZetaWatch repository contains the source code, not the finished program. Please download one of the binary releases from https://github.com/cbreak-black/ZetaWatch/releases and install it in Applications. After starting the Program, you should see the Z icon in the menu bar. You can then select "Start at Login" in the "Settings" menu. (It should be on by default.)

If you actually want to compile the program, you'll have to prepare suitable ZFS source trees, and have to set up a Mac OS dev env with apple-approved signing keys.

**Comment by UnConundrum** [comment]
THX!

Totally missed the releases tab.
